# Generated by Django 3.1 on 2020-09-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufo', '0004_event_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='area',
            field=models.CharField(max_length=100),
        ),
    ]
