# Generated by Django 3.1 on 2020-10-17 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ufo', '0005_auto_20200903_0912'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
